/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-07-26 13:57:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/admin/../includes/admin/header.jsp", Long.valueOf(1658804690611L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1657518318415L));
    _jspx_dependants.put("jar:file:/D:/JAVA_SW/projectTeam4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/projectTeam4/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/admin/../includes/admin/footer.jsp", Long.valueOf(1658804690604L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/admin/main.css\">\r\n");
      out.write(" \r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.4.1.js\"\r\n");
      out.write("  integrity=\"sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" \r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        <div class=\"wrap\">\r\n");
      out.write("            <!-- gnv_area -->    \r\n");
      out.write("            <div class=\"top_gnb_area\">\r\n");
      out.write("                <ul class=\"list\">    \r\n");
      out.write("                    <li><a href=\"/main\">메인 페이지</a></li>\r\n");
      out.write("                    <li><a href=\"/member/logout.do\">로그아웃</a></li>\r\n");
      out.write("                    <li>고객센터</li>            \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- top_subject_area -->\r\n");
      out.write("            <div class=\"admin_top_wrap\">\r\n");
      out.write("                <span>관리자 페이지</span>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- contents-area -->\r\n");
      out.write("            <div class=\"admin_wrap\">\r\n");
      out.write("                <!-- 네비영역 -->\r\n");
      out.write("                <div class=\"admin_navi_wrap\">\r\n");
      out.write("                  <ul>\r\n");
      out.write("                      <li >\r\n");
      out.write("                          <a class=\"admin_list_01\" href=\"/admin/productEnroll\">상품 등록</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li>\r\n");
      out.write("                          <a class=\"admin_list_02\" href=\"/admin/productManage\">상품 관리</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <lI>\r\n");
      out.write("                          <a class=\"admin_list_03\" href=\"/admin/memberEnroll\">회원 등록</a>                            \r\n");
      out.write("                      </lI>\r\n");
      out.write("                      <lI>\r\n");
      out.write("                          <a class=\"admin_list_04\" href=\"/admin/memberManage\">회원 관리</a>                            \r\n");
      out.write("                      </lI>\r\n");
      out.write("                      <lI>\r\n");
      out.write("                          <a class=\"admin_list_05\" href=\"/admin/notice/list\">게시판</a>                            \r\n");
      out.write("                      </lI>                                                                                             \r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("                <div class=\"admin_content_wrap\">\r\n");
      out.write("                    <div>관리자 페이지 입니다.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("     <div class=\"clearfix\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer 영역 -->\r\n");
      out.write("        <div class=\"footer_nav\">\r\n");
      out.write("            <div class=\"footer_nav_container\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>회사소개</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>이용약관</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>고객센터</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>광고문의</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>채용정보</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> <!-- class=\"footer_nav\" -->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"footer\">\r\n");
      out.write("            <div class=\"footer_container\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"footer_left\">\r\n");
      out.write("                    <img src=\"../../resources/img/logo.jpg\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer_right\">\r\n");
      out.write("                    (주) 팔도주류    대표이사 : 4팀\r\n");
      out.write("                    <br>\r\n");
      out.write("                    사업자등록번호 : ooo-oo-ooooo\r\n");
      out.write("                    <br>\r\n");
      out.write("                    대표전화 : 010-4161-7059\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    COPYRIGHT(C) <strong>www.paldo.com</strong>    ALL RIGHTS RESERVED.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"clearfix\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> <!-- class=\"footer\" -->    ");
      out.write("\r\n");
      out.write(" <script>\r\n");
      out.write(" \r\n");
      out.write("    /* gnb_area 로그아웃 버튼 작동 */\r\n");
      out.write("    $(\"#gnb_logout_button\").click(function(){\r\n");
      out.write("        alert(\"버튼 작동\");\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            type:\"POST\",\r\n");
      out.write("            url:\"/admin/logout.do\",\r\n");
      out.write("            success:function(data){\r\n");
      out.write("                alert(\"로그아웃 성공\");\r\n");
      out.write("                document.location.reload();     \r\n");
      out.write("            } \r\n");
      out.write("        }); // ajax \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
