/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-07-26 16:55:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productEnroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/admin/../includes/admin/header.jsp", Long.valueOf(1658804690611L));
    _jspx_dependants.put("jar:file:/D:/JAVA_SW/projectTeam4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/projectTeam4/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1657518318415L));
    _jspx_dependants.put("jar:file:/D:/JAVA_SW/projectTeam4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/projectTeam4/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/admin/../includes/admin/footer.jsp", Long.valueOf(1658804690604L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"../../../resources/css/admin/productEnroll.css\">\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.6.0.js\"\r\n");
      out.write("  integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\r\n");
      out.write("  crossorigin=\"anonymous\">\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#result_card img {\r\n");
      out.write("	max-width: 100%;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	display: block;\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#result_card {\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".imgDeleteBtn {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	right: 5%;\r\n");
      out.write("	background-color: #ef7d7d;\r\n");
      out.write("	color: wheat;\r\n");
      out.write("	font-weight: 900;\r\n");
      out.write("	width: 30px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	line-height: 26px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	border: none;\r\n");
      out.write("	display: block;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        <div class=\"wrap\">\r\n");
      out.write("            <!-- gnv_area -->    \r\n");
      out.write("            <div class=\"top_gnb_area\">\r\n");
      out.write("                <ul class=\"list\">    \r\n");
      out.write("                    <li><a href=\"/main\">메인 페이지</a></li>\r\n");
      out.write("                    <li><a href=\"/member/logout.do\">로그아웃</a></li>\r\n");
      out.write("                    <li>고객센터</li>            \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- top_subject_area -->\r\n");
      out.write("            <div class=\"admin_top_wrap\">\r\n");
      out.write("                <span>관리자 페이지</span>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- contents-area -->\r\n");
      out.write("            <div class=\"admin_wrap\">\r\n");
      out.write("                <!-- 네비영역 -->\r\n");
      out.write("                <div class=\"admin_navi_wrap\">\r\n");
      out.write("                  <ul>\r\n");
      out.write("                      <li >\r\n");
      out.write("                          <a class=\"admin_list_01\" href=\"/admin/productEnroll\">상품 등록</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li>\r\n");
      out.write("                          <a class=\"admin_list_02\" href=\"/admin/productManage\">상품 관리</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <lI>\r\n");
      out.write("                          <a class=\"admin_list_03\" href=\"/admin/memberEnroll\">회원 등록</a>                            \r\n");
      out.write("                      </lI>\r\n");
      out.write("                      <lI>\r\n");
      out.write("                          <a class=\"admin_list_04\" href=\"/admin/memberManage\">회원 관리</a>                            \r\n");
      out.write("                      </lI>\r\n");
      out.write("                      <lI>\r\n");
      out.write("                          <a class=\"admin_list_05\" href=\"/admin/notice/list\">게시판</a>                            \r\n");
      out.write("                      </lI>                                                                                             \r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"admin_content_wrap\">\r\n");
      out.write("		<div class=\"admin_content_subject\">\r\n");
      out.write("			<scan>상품 등록</scan>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"admin_content_main\">\r\n");
      out.write("			<form role=\"form\" action=\"/admin/productEnroll\" method=\"post\" id=\"productForm\">\r\n");
      out.write("				<div class=\"form_section\">\r\n");
      out.write("					<div class=\"form_section_title\">\r\n");
      out.write("						<label>상품 아이디</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form_section_content\">\r\n");
      out.write("						<input name=\"productId\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section\">\r\n");
      out.write("					<div class=\"form_section_title\">\r\n");
      out.write("						<label>회사 아이디</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form_section_content\">\r\n");
      out.write("						<input name=\"companyId\" value=\"0\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section\">\r\n");
      out.write("					<div class=\"form_section_title\">\r\n");
      out.write("						<label>상품이름</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form_section_content\">\r\n");
      out.write("						<input name=\"productName\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section\">\r\n");
      out.write("					<div class=\"form_section_title\">\r\n");
      out.write("						<label>재고</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form_section_content\">\r\n");
      out.write("						<input name=\"stock\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section\">\r\n");
      out.write("					<div class=\"form_section_title\">\r\n");
      out.write("						<label>가격</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form_section_content\">\r\n");
      out.write("						<input name=\"price\" value=\"0\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section\">\r\n");
      out.write("					<div class=\"form_section_title\">\r\n");
      out.write("						<label>할인율</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input id=\"discount_interface\" maxlength=\"2\" value=\"0\"> <input\r\n");
      out.write("						name=\"discount\" type=\"hidden\" value=\"0\"> <span\r\n");
      out.write("						class=\"step_val\">할인 가격 : <span class=\"span_discount\"></span></span>\r\n");
      out.write("				</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"form_section\">\r\n");
      out.write("			<div class=\"form_section_title\">\r\n");
      out.write("				<label>최종 가격</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form_section_content\">\r\n");
      out.write("				<input name=\"lastPrice\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"form_section\">\r\n");
      out.write("			<div class=\"form_section_title\">\r\n");
      out.write("				<label>상품 이미지</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form_section_content\">\r\n");
      out.write("				<input type=\"file\" name='uploadFile' multiple>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class='uploadResult'></div>\r\n");
      out.write("			<div class=\"btn_section\">\r\n");
      out.write("				<input type=\"submit\">\r\n");
      out.write("				<button type=\"button\" onclick=\"location.href = 'main' \">취소</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"admin_content_wrap\">\r\n");
      out.write("			<div class=\"admin_content_subject\">\r\n");
      out.write("				<span>상품 등록</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("     <div class=\"clearfix\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer 영역 -->\r\n");
      out.write("        <div class=\"footer_nav\">\r\n");
      out.write("            <div class=\"footer_nav_container\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>회사소개</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>이용약관</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>고객센터</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>광고문의</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>채용정보</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> <!-- class=\"footer_nav\" -->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"footer\">\r\n");
      out.write("            <div class=\"footer_container\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"footer_left\">\r\n");
      out.write("                    <img src=\"../../resources/img/logo.jpg\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer_right\">\r\n");
      out.write("                    (주) 팔도주류    대표이사 : 4팀\r\n");
      out.write("                    <br>\r\n");
      out.write("                    사업자등록번호 : ooo-oo-ooooo\r\n");
      out.write("                    <br>\r\n");
      out.write("                    대표전화 : 010-4161-7059\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    COPYRIGHT(C) <strong>www.paldo.com</strong>    ALL RIGHTS RESERVED.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"clearfix\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> <!-- class=\"footer\" -->    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("$(document).ready(function(e){\r\n");
      out.write("	var formObj = $(\"form[role='form']\");\r\n");
      out.write("	$(\"button[id='submit']\").on(\"click\", function(e){\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		console.log(\"submit clicked\");\r\n");
      out.write("		\r\n");
      out.write("		var str =\"\";\r\n");
      out.write("	$(\".uploadResult ul li\").each(function(e){\r\n");
      out.write("		var jobj = $(obj);\r\n");
      out.write("		console.dir(jobj);\r\n");
      out.write("		\r\n");
      out.write("		str += \"<input type='hidden' name = 'imageVO[\"+i+\"].fileName' value ='\"+jobj.data(\"filename\")+\"'>\";\r\n");
      out.write("		str += \"<input type='hidden' name = 'imageVO[\"+i+\"].uuid' value ='\"+jobj.data(\"uuid\")+\"'>\";\r\n");
      out.write("		str += \"<input type='hidden' name = 'imageVO[\"+i+\"].uploadPath' value ='\"+jobj.data(\"uploadPath\")+\"'>\";\r\n");
      out.write("		str += \"<input type='hidden' name = 'imageVO[\"+i+\"].fileFormat' value ='\"+jobj.data(\"fileFormat\")+\"'>\";\r\n");
      out.write("		});\r\n");
      out.write("		formObj.append(str).submit;\r\n");
      out.write("		$(\"#productForm\").submit();\r\n");
      out.write("	});\r\n");
      out.write("	var regex = new RegExp(\"(.*?)\\.(jpg|png|gif|JPG|PNG|GIF)$\");\r\n");
      out.write("	var maxSize = 5242880;\r\n");
      out.write("	\r\n");
      out.write("	function checkExtendsion(fileName, fileSize){\r\n");
      out.write("		if(fileSize >= maxSize){\r\n");
      out.write("			alert(\"파일 사이즈 초과\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if(!regex.test(fileName)){\r\n");
      out.write("			alert(\"해당 종류의 파일은 업로드 할 수 없습니다.\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("	$(\"input[type='file']\").change(function(e){\r\n");
      out.write("		\r\n");
      out.write("		var formData = new FormData();\r\n");
      out.write("		var inputFile = $(\"input[name='uploadFile']\");\r\n");
      out.write("		var files = inputFile[0].files;\r\n");
      out.write("		for(var i = 0; i <files.length; i++){\r\n");
      out.write("			if(!checkExtendsion(files[i].name, files[i].size)){\r\n");
      out.write("				\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			formData.append(\"uploadFile\",files[i]);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: '/uploadAjaxAction',\r\n");
      out.write("			processData: false,\r\n");
      out.write("			contentType: false,\r\n");
      out.write("			data: formData,\r\n");
      out.write("			type:'POST',\r\n");
      out.write("			dataType: 'json',\r\n");
      out.write("			success: function(result){\r\n");
      out.write("				console.log(result);\r\n");
      out.write("				showUploadResult(result);\r\n");
      out.write("			}\r\n");
      out.write("		}); //$.ajax\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	function showUploadResult(uploadResultArr){\r\n");
      out.write("		if(!uploadResultArr || uploadResultArr.length == 0){retrun;}\r\n");
      out.write("		\r\n");
      out.write("		var uploadUL = $(\".uploadResult ul\");\r\n");
      out.write("		var str =\"\";\r\n");
      out.write("		\r\n");
      out.write("		$(uploadResultArr).each(function(i, obj){\r\n");
      out.write("			if(obj.image){\r\n");
      out.write("			var fileCallPath = encodeURIComponent( obj.uploadPath+\"/\"+\"s_\"+obj.uuid+\"_\"+obj.fileName);\r\n");
      out.write("			str += \"<li data-path='\"+obj.uploadPath+\"'\";\r\n");
      out.write("			str += \" data-uuid='\"+obj.uuid+\"' data-filename='\"+obj.fileName+\"' data-type='\"+obj.image+\"'\"\r\n");
      out.write("			str += \"><div>\";\r\n");
      out.write("			str += \"<span> \"+obj.fileName+\"</span>\"\r\n");
      out.write("			str += \"<button type='button' data-file=\\'\"+fileCallPath+\"\\' data-type='imgae' calss='btn btn-warning btn-circle'><i class='fa fa-times'></i></button><br>\";\r\n");
      out.write("			str += \"<img src='/display?fileName=\"+fileCallPath+\"'>\";\r\n");
      out.write("			str += \"</div>\";\r\n");
      out.write("			str +\"</li>\";\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		uploadUL.append(str);\r\n");
      out.write("	}\r\n");
      out.write("	$(\".uploadResult\").on(\"click\",\"button\",function(e){\r\n");
      out.write("		console.log(\"delete file\");\r\n");
      out.write("		var targetFile = $(this).data(\"file\");\r\n");
      out.write("		var type = $(this).data(\"type\");\r\n");
      out.write("		var targetLi = $(this).closest(\"li\");\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: '/deleteFile',\r\n");
      out.write("			data: {fileName: targetFile, type:type},\r\n");
      out.write("			dataType: 'text',\r\n");
      out.write("			type: 'POST',\r\n");
      out.write("			success: function(result){\r\n");
      out.write("				alert(result);\r\n");
      out.write("				targetLi.remove();\r\n");
      out.write("				}\r\n");
      out.write("			}); //$.ajax\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("/* 취소 버튼\r\n");
      out.write("$(\"#cancelBtn\").click(function(){\r\n");
      out.write("	\r\n");
      out.write("	location.href=\"/admin/main;\"\r\n");
      out.write("	\r\n");
      out.write("});\r\n");
      out.write("/* 상품 등록 버튼 \r\n");
      out.write("$(\"#enrollBtn\").on(\"click\",function(e){\r\n");
      out.write("	\r\n");
      out.write("	e.preventDefault();\r\n");
      out.write("	var str = \"\";*/\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("/* 할인율 Input 설정 */\r\n");
      out.write("$(\"#discount_interface\").on(\"propertychange change keyup paste input\", function(){\r\n");
      out.write("	\r\n");
      out.write("	let userInput = $(\"#discount_interface\");\r\n");
      out.write("	let discountInput = $(\"input[name='discount']\");\r\n");
      out.write("	\r\n");
      out.write("	let discountRate = userInput.val();					// 사용자가 입력할 할인값\r\n");
      out.write("	let sendDiscountRate = discountRate / 100;					// 서버에 전송할 할인값\r\n");
      out.write("	let price = $(\"input[name='price']\").val();			// 원가\r\n");
      out.write("	let lastPrice = price * (1 - sendDiscountRate);		// 할인가격\r\n");
      out.write("	        \r\n");
      out.write("	$(\".span_discount\").html(lastPrice);\r\n");
      out.write("	\r\n");
      out.write("	discountInput.val(sendDiscountRate);	\r\n");
      out.write("	\r\n");
      out.write("});	\r\n");
      out.write("\r\n");
      out.write("$(\"input[name='price']\").on(\"change\", function(){\r\n");
      out.write("	\r\n");
      out.write("	let userInput = $(\"#discount_interface\");\r\n");
      out.write("	let discountInput = $(\"input[name='discount']\");\r\n");
      out.write("	\r\n");
      out.write("	let discountRate = userInput.val();					// 사용자가 입력한 할인값\r\n");
      out.write("	let sendDiscountRate = discountRate / 100;			// 서버에 전송할 할인값\r\n");
      out.write("	let price = $(\"input[name='price']\").val();			// 원가\r\n");
      out.write("	let lastPrice = price * (1 - sendDiscountRate);		// 할인가격\r\n");
      out.write("	\r\n");
      out.write("	$(\".span_discount\").html(lastPrice);\r\n");
      out.write("	\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
